/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wl.testaction;



import java.sql.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.wl.forms.Parts;

public class AddpartsAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		Parts parts = (Parts) form;
		
		String part_id = request.getParameter("part_id");
		String part_pid = request.getParameter("part_pid");
		String starttime = request.getParameter("starttime");
		String endtime = request.getParameter("endtime");
		String preparetime = request.getParameter("preparetime");
		String plantime = request.getParameter("plantime");
		String peoplenm = request.getParameter("peoplenm");
		String picnm = request.getParameter("picnm");
		
		String sql = "insert into user_test value('"+part_id+"','"+part_pid+"','"+starttime+"','"+endtime+"','"+preparetime+"','"+plantime+"','"+peoplenm+"','"+picnm+"')";
		
		System.out.println(sql);
		
		return mapping.findForward("addparts");
	}
}