/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wl.testaction;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.*;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.wl.forms.Parts;
import com.wl.forms.Tree;
import com.wl.tools.Sqlhelper;

public class IntomainAction extends Action {
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String sql = "select *from tree where 1=?";
		String paras[]={"1"};
		ResultSet rs=null;
		try {
			rs = Sqlhelper.executeQuery(sql, paras);
		} catch (SQLException e1) {
			e1.printStackTrace();
		}
		ArrayList<Tree> trees= new ArrayList<Tree>();
		try {
			while(rs.next()){  
				Tree tree= new Tree();
				tree.setTree_id(rs.getString(1));
				tree.setTree_pid(rs.getString(2));
				tree.setTree_name(rs.getString(3));
				trees.add(tree);
			} 
			request.setAttribute("tree", trees);
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
			System.out.println("���ת��������");
		} finally{
			try {
				if(rs!=null){
					rs.close();
				}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		System.out.println("����intomainaction���Ѿ�");
		return mapping.findForward("maintree");
	}
}