/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wl.testaction;

import java.io.UnsupportedEncodingException;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.wl.forms.Partplan;
import com.wl.tools.Sqlhelper;

public class Partplan_operAction extends DispatchAction {

	public ActionForward query_partplan(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		Partplan partPlan = (Partplan) form;// TODO Auto-generated method stub
//		String pid = request.getParameter("id").toString();
		String sql = "select *from partplan";
//		String paras[]={pid};
		ResultSet rs=null;
		try {
			rs = (ResultSet) Sqlhelper.executeQuery(sql, null);
		} catch (SQLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		ArrayList<Partplan> al = new ArrayList<Partplan>();	
		try {
			while(rs.next()){
				Partplan partplan=new Partplan();
				partplan.setOrderID(rs.getString(1));
				partplan.setProductID(rs.getString(2));
				partplan.setIssuenum(rs.getString(3));
				partplan.setPlanid(rs.getInt(4));
				partplan.setItemid(rs.getString(5));
				partplan.setQualityid(rs.getString(6));
				partplan.setFatheritemid(rs.getString(7));
				partplan.setPlanpeo(rs.getString(8));
				partplan.setPlantime(rs.getString(9));
				partplan.setPartnum(rs.getInt(10));
				partplan.setPartbegintime(rs.getDate(11));
				partplan.setPartendtime(rs.getDate(12));
				partplan.setPartstatus(rs.getString(13));
				partplan.setCodeid(rs.getString(14));
				partplan.setCanclestatus(rs.getString(15));
				partplan.setFinishnum(rs.getInt(16));
				partplan.setDepatchpro(rs.getString(17));
				partplan.setPassnum(rs.getInt(18));
				partplan.setFailurenum(rs.getInt(19));
				partplan.setFinishration(rs.getFloat(20));
				partplan.setIsreceive(rs.getString(21));
				partplan.setReceivedate(rs.getDate(22));
				partplan.setReceiverate(rs.getFloat(23));
				partplan.setToolstatus(rs.getString(24));
				partplan.setCutstatus(rs.getString(25));
				partplan.setMeasurestatus(rs.getString(26));
				partplan.setMtlstatus(rs.getString(27));
				partplan.setAccessorystatus(rs.getString(28));
				partplan.setShelflife(rs.getFloat(29));
				partplan.setCheckinnum(rs.getInt(30));
				partplan.setCheckoutnum(rs.getInt(31));
				partplan.setMovequity(rs.getInt(32));
				partplan.setCheckindate(rs.getDate(33));
				partplan.setPosttime(rs.getString(34));
				partplan.setIschange(rs.getInt(35));
				partplan.setCheckstatus(rs.getString(36));
				partplan.setWlreceive(rs.getString(37));
				partplan.setPartplana(rs.getString(38));
				partplan.setPartplanb(rs.getString(39));
                partplan.setMemo(rs.getString(40));
                partplan.setPartname(rs.getString(42));
                partplan.setPlan_time(rs.getDate(43));
                partplan.setPeoplenum(rs.getInt(44));
                partplan.setPicturenum(rs.getString(45));
				
				al.add(partplan);
			}
			
		} catch (Exception e) {
			e.printStackTrace();
			System.out.println("partplanת����arraylist��������");
		} finally{
			try {
				if(rs!=null){
					rs.close();
				}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

		System.out.println("����partplan query���Ѿ�����");

		try {
			request.setCharacterEncoding("utf-8");
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			System.out.println("�ַ�ת���쳣������");
		}
		request.setAttribute("partplan", al);
		return mapping.findForward("query_partplan");
	}
}