/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wl.testaction;

import java.io.UnsupportedEncodingException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.wl.forms.Item;
import com.wl.forms.ProcessPlan;
import com.wl.tools.Sqlhelper;

public class ToitemListAction extends DispatchAction {

	public ActionForward QueryitemList(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		System.out.println("����ToitemListAction��itemList���������Ѿ�������");
		String sql = "select *from item";
//		String paras[]={pid};
		ResultSet rs=null;
		try {
			rs = (ResultSet) Sqlhelper.executeQuery(sql, null);
		} catch (SQLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		ArrayList<Item> al = new ArrayList<Item>();	
		try {
			while(rs.next()){
				Item item=new Item();
				item.setItemid(rs.getString(1));
				item.setItemtypeid(rs.getString(2));
				item.setItemname(rs.getString(3));
				item.setItemdrawing(rs.getString(4));
				item.setMaterialmark(rs.getString(5));
				item.setItemattri(rs.getString(6));
				item.setItemspecification(rs.getString(7));
				item.setItemmb(rs.getString(8));
				item.setItemstatus(rs.getString(9));
				item.setUnitm(rs.getString(10));
				item.setLotsize(rs.getInt(11));
				item.setOrdermin(rs.getFloat(12));
				item.setLeadtime(rs.getFloat(13));
				item.setVarleadtime(rs.getFloat(14));
				item.setAbccode(rs.getString(15));
				item.setLLc(rs.getInt(16));
				item.setSafestock(rs.getInt(17));
				item.setStockhigh(rs.getInt(18));
				item.setStocklow(rs.getInt(19));
				item.setMpsflag(rs.getFloat(20));
				//item.setPhantomunit(rs.getFloat(21));
				item.setItemunit(rs.getString(22));
				item.setWeightunit(rs.getString(23));
				item.setYeild(rs.getFloat(24));
				item.setPtype(rs.getString(25));
				item.setPurchaseunite(rs.getString(26));
				item.setPlanunite(rs.getFloat(27));
				item.setSubproduct(rs.getFloat(28));
				item.setAssembleafterall(rs.getFloat(29));
				item.setCostmethod(rs.getString(30));
				item.setDaysmultiple(rs.getFloat(31));
				item.setBackflash(rs.getFloat(32));
				item.setItemprice(rs.getFloat(33));
				item.setPriceunit(rs.getString(34));
				item.setCurrency(rs.getString(35));
				item.setRmbprice(rs.getFloat(36));
				item.setExtraA(rs.getString(37));
				item.setExtraB(rs.getString(38));
				item.setDymtlmark(rs.getString(39));
				item.setMemo(rs.getString(40));
				item.setMtlsort(rs.getString(41));
				item.setItemA(rs.getString(42));
				item.setItemB(rs.getString(43));
				item.setItemC(rs.getString(44));
				item.setItemD(rs.getString(45));
	
				al.add(item);
			}
			
		} catch (Exception e) {
			e.printStackTrace();
			System.out.println("Itemת����arraylist��������");
		} finally{
			try {
				if(rs!=null){
					rs.close();
				}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		try {
			request.setCharacterEncoding("utf-8");
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			System.out.println("�ַ�ת���쳣������");
		}
		request.setAttribute("itemList", al);
		return mapping.findForward("toitemList");
	}
}