/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wl.testaction;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.*;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import JSOM.DB;
import JSOM.JackSonTrans;
import JSOM.TransTask;
import com.sun.xml.internal.ws.message.stream.PayloadStreamReaderMessage;
import org.omg.PortableInterceptor.SYSTEM_EXCEPTION;

public class WlactionAction extends DispatchAction {

	public ActionForward wanglu(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub

	    
	    try {
			BufferedReader reader = request.getReader();
			StringBuffer buffer = new StringBuffer();
			String string;
			while ((string = reader.readLine()) != null) {
				buffer.append(string);
			}
			System.out.println("�������"+buffer.toString());
		    response.getWriter().append(buffer.toString());			
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
			System.out.println("wlaction ��ת�쳣������");
		}
		return null;
	}

	public ActionForward load(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		try {
			response.getWriter().append(JackSonTrans.JsonBack(DB.getFandTList()));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			System.out.println("wlaction �� load�����쳣������");
		}
		System.out.println("������wlaction��load���������Ѿ�������");
		return null;
	}
	
	public ActionForward save(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		System.out.println("开始保存！！！！！");
//		try {
//			BufferedReader reader = request.getReader();
//			StringBuffer buffer = new StringBuffer();
//			String string;
//			while ((string = reader.readLine()) != null) {
//				buffer.append(string);
//			}
//		    JackSonTrans.PrintFandTList(JackSonTrans.ListBack(buffer.toString()));
//		    DB.saveFandTList(JackSonTrans.ListBack(buffer.toString()));
//		    response.getWriter().append(buffer.toString());
//		} catch (Exception e) {
//			// TODO: handle exception
//			e.printStackTrace();
//			System.out.println("wlaction的save出现异常！！！");
//		}
		return null;
	}
}