/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wl.testaction;

import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.wl.tools.Sqlhelper;

public class Work_processplanAction extends DispatchAction {

	public ActionForward addprocess(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws UnsupportedEncodingException {
		// TODO Auto-generated method stub
		request.setCharacterEncoding("utf-8");
		
		System.out.println("进入Work_processplanAction的addprocess函数体了已经!!!");
		String processid=request.getParameter("processid");
		String productid=request.getParameter("productid");
		String starttime=request.getParameter("starttime");
		String finishtime=request.getParameter("finishtime");
		
		//下面一部分代码是用来解决中文乱码的问题的！！！！！！！！！！
		String processplan_a=new String(request.getParameter("processplan_a").getBytes("ISO-8859-1"),"utf-8");
		System.out.println("processplan_a==="+processplan_a);
		System.out.println("processplan_a转化后的结果=="+new String(processplan_a.getBytes("utf-8"),"utf-8"));
		String processplan_b=new String(request.getParameter("processplan_b").getBytes("ISO-8859-1"),"utf-8");
		System.out.println("processplan_b==="+processplan_b);
		System.out.println("processplan_b转化后的结果=="+new String(processplan_a.getBytes("ISO-8859-1"),"utf-8"));
		String plan_id=request.getParameter("plan_id");

		String sql ="insert into process(OPER_ID,EQUIPMENT_DRAWID,START_TIME,END_TIME,processplan_a,processplan_b,plan_id) values('"
			+processid+"','"+productid+"',to_date('"+starttime+"','yyyy-mm-dd,hh24:mi:ss'),to_date('"+
			finishtime+"','yyyy-mm-dd,hh24:mi:ss'),'"+processplan_a+"','"+processplan_b+"','"+plan_id+"')";
		
		System.out.println("插入工序的sql++"+sql);
		System.out.println("插入工序的sql++");
		
		try {
			Sqlhelper.executeUpdate(sql, null);
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
			System.out.println("Add_process_planAction出现异常！！！");
			return mapping.findForward("err");
		}
		
		
		return mapping.findForward("ok");
	}
}