/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wl.testaction;

import java.sql.ResultSet;
import java.sql.SQLException;

import oracle.sql.DATE;

import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import com.wl.forms.Parts;
import com.wl.tools.Sqlhelper;

public class Workplan_dispAction extends DispatchAction {

public ActionForward show(ActionMapping mapping, ActionForm form,
		HttpServletRequest request, HttpServletResponse response) {
		//Parts partbean = (Parts) form;// TODO Auto-generated method stub
		String id = request.getParameter("id").toString();
		String sql = "select *from parts where id=?";
		String paras[]={id};
		ResultSet rs=null;
		try {
			rs = (ResultSet) Sqlhelper.executeQuery(sql, paras);
		} catch (SQLException e1) {
			e1.printStackTrace();
		}
		Parts part=new Parts();
		System.out.println("����parts  disp action���Ѿ�������");
		try {
			while(rs.next()){
				part.setPart_id(rs.getString(1));
//				System.out.println(rs.getString(1));
				part.setPart_pid(rs.getString(2));
				part.setStarttime(rs.getDate(3));
				part.setEndtime(rs.getDate(4));
				part.setPreparetime(rs.getDate(5));
				part.setPlantime(rs.getDate(6));
				part.setPeoplenm(rs.getInt(7));
				part.setPicnm(rs.getString(8));
			}	
		} catch (Exception e) {
			System.out.println(e);
			System.out.println("ת����������");
		}finally{
			try {
				if(rs!=null){
					rs.close();
				}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		request.setAttribute("parts", part);
		return mapping.findForward("workplan");
	}

	public ActionForward add (ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response){
		Parts parts =(Parts)form;
		System.out.println("����add������");
		String part_id = request.getParameter("part_id");
		String part_pid = request.getParameter("part_pid");
		String starttime = request.getParameter("starttime");
		String endtime = request.getParameter("endtime");
		String preparetime = request.getParameter("preparetime");
		String plantime = request.getParameter("plantime");
		String peoplenm = request.getParameter("peoplenm");
		String picnm = request.getParameter("picnm");
		
		String sql ="insert into parts values('"+part_id+"','"+part_pid+"',to_date('"+starttime+"','yyyy-mm-dd'),to_date('"+endtime+"','yyyy-mm-dd'),to_date('"+preparetime+"','yyyy-mm-dd'),to_date('"+plantime+"','yyyy-mm-dd'),"+peoplenm+",'"+picnm+"')";
		
		System.out.println(sql);
		
		try {
			Sqlhelper.executeUpdate(sql, null);
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
			System.out.println("���parts�쳣������");
			return mapping.findForward("err");
		}
		
		return mapping.findForward("addparts");
	}
}







